export default {
  HOME: 'Home',
  SPLASHSCREEN: 'SplashScreen',
  AUTH: 'Auth',
  PROFILE: 'Profile',
  PROJECTS: 'All Projects',
  DRAWER : 'darwer',
  BOTTOM_TABS : "bottom tabs",
  CHATS : "Chats",
  DISCUSSION : "Discussion",
  SUBPROJECTS : "Sub Section",
  QUESTION_DETAILS : "question details",
  SUBPROJECTSTABS : "Sub project",
  PROFILEDETAILS : "Profile",
  CHATS_SCREEN :"Chat",
  SUBPROJECT:"Sub Project Section",
  SUBDISCUSSION :"Project Discussion",
  SUBPROJECT_QUESTION:"Sub Project Question",
  INVITE_ADMIN : "Invite Admin",
  SINGLE_CHAT : "single chat",
  SUB_PRO_SINGLE_CHAT :"Sub Pro single Chat",
  SUB_PRO_CHAT : "sub project chats",
  TIME_LINE :"Activity",
  SUB_TIME_LINE :"Activity_"
 };
